/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'base',
    path: '/base',
    component: 'layout.base',
    meta: {
      title: 'base',
      i18nKey: 'route.base'
    },
    children: [
      {
        name: 'base_business-type',
        path: '/base/business-type',
        component: 'view.base_business-type',
        meta: {
          title: 'base_business-type',
          i18nKey: 'route.base_business-type'
        }
      },
      {
        name: 'base_channel',
        path: '/base/channel',
        component: 'view.base_channel',
        meta: {
          title: 'base_channel',
          i18nKey: 'route.base_channel'
        }
      },
      {
        name: 'base_city',
        path: '/base/city',
        component: 'view.base_city',
        meta: {
          title: 'base_city',
          i18nKey: 'route.base_city'
        }
      },
      {
        name: 'base_company',
        path: '/base/company',
        component: 'view.base_company',
        meta: {
          title: 'base_company',
          i18nKey: 'route.base_company'
        }
      },
      {
        name: 'base_country',
        path: '/base/country',
        component: 'view.base_country',
        meta: {
          title: 'base_country',
          i18nKey: 'route.base_country'
        }
      },
      {
        name: 'base_currency',
        path: '/base/currency',
        component: 'view.base_currency',
        meta: {
          title: 'base_currency',
          i18nKey: 'route.base_currency'
        }
      },
      {
        name: 'base_exchange-rate',
        path: '/base/exchange-rate',
        component: 'view.base_exchange-rate',
        meta: {
          title: 'base_exchange-rate',
          i18nKey: 'route.base_exchange-rate'
        }
      },
      {
        name: 'base_fee-item',
        path: '/base/fee-item',
        component: 'view.base_fee-item',
        meta: {
          title: 'base_fee-item',
          i18nKey: 'route.base_fee-item'
        }
      },
      {
        name: 'base_platform',
        path: '/base/platform',
        component: 'view.base_platform',
        meta: {
          title: 'base_platform',
          i18nKey: 'route.base_platform'
        }
      },
      {
        name: 'base_platform-address',
        path: '/base/platform-address',
        component: 'view.base_platform-address',
        meta: {
          title: 'base_platform-address',
          i18nKey: 'route.base_platform-address'
        }
      },
      {
        name: 'base_port',
        path: '/base/port',
        component: 'view.base_port',
        meta: {
          title: 'base_port',
          i18nKey: 'route.base_port'
        }
      },
      {
        name: 'base_shipping-line',
        path: '/base/shipping-line',
        component: 'view.base_shipping-line',
        meta: {
          title: 'base_shipping-line',
          i18nKey: 'route.base_shipping-line'
        }
      },
      {
        name: 'base_shipping-route',
        path: '/base/shipping-route',
        component: 'view.base_shipping-route',
        meta: {
          title: 'base_shipping-route',
          i18nKey: 'route.base_shipping-route'
        }
      },
      {
        name: 'base_sku',
        path: '/base/sku',
        component: 'view.base_sku',
        meta: {
          title: 'base_sku',
          i18nKey: 'route.base_sku'
        }
      },
      {
        name: 'base_state-province',
        path: '/base/state-province',
        component: 'view.base_state-province',
        meta: {
          title: 'base_state-province',
          i18nKey: 'route.base_state-province'
        }
      },
      {
        name: 'base_terminal',
        path: '/base/terminal',
        component: 'view.base_terminal',
        meta: {
          title: 'base_terminal',
          i18nKey: 'route.base_terminal'
        }
      },
      {
        name: 'base_timezone',
        path: '/base/timezone',
        component: 'view.base_timezone',
        meta: {
          title: 'base_timezone',
          i18nKey: 'route.base_timezone'
        }
      },
      {
        name: 'base_value-added-service',
        path: '/base/value-added-service',
        component: 'view.base_value-added-service',
        meta: {
          title: 'base_value-added-service',
          i18nKey: 'route.base_value-added-service'
        }
      },
      {
        name: 'base_vessel',
        path: '/base/vessel',
        component: 'view.base_vessel',
        meta: {
          title: 'base_vessel',
          i18nKey: 'route.base_vessel'
        }
      },
      {
        name: 'base_warehouse',
        path: '/base/warehouse',
        component: 'view.base_warehouse',
        meta: {
          title: 'base_warehouse',
          i18nKey: 'route.base_warehouse'
        }
      },
      {
        name: 'base_zip-code',
        path: '/base/zip-code',
        component: 'view.base_zip-code',
        meta: {
          title: 'base_zip-code',
          i18nKey: 'route.base_zip-code'
        }
      }
    ]
  },
  {
    name: 'comm',
    path: '/comm',
    component: 'layout.base',
    meta: {
      title: 'comm',
      i18nKey: 'route.comm'
    },
    children: [
      {
        name: 'comm_ai',
        path: '/comm/ai',
        component: 'view.comm_ai',
        meta: {
          title: 'comm_ai',
          i18nKey: 'route.comm_ai'
        }
      },
      {
        name: 'comm_archive',
        path: '/comm/archive',
        component: 'view.comm_archive',
        meta: {
          title: 'comm_archive',
          i18nKey: 'route.comm_archive'
        }
      },
      {
        name: 'comm_business-session',
        path: '/comm/business-session',
        component: 'view.comm_business-session',
        meta: {
          title: 'comm_business-session',
          i18nKey: 'route.comm_business-session'
        }
      },
      {
        name: 'comm_contacts',
        path: '/comm/contacts',
        component: 'view.comm_contacts',
        meta: {
          title: 'comm_contacts',
          i18nKey: 'route.comm_contacts'
        }
      },
      {
        name: 'comm_file',
        path: '/comm/file',
        component: 'view.comm_file',
        meta: {
          title: 'comm_file',
          i18nKey: 'route.comm_file'
        }
      },
      {
        name: 'comm_group',
        path: '/comm/group',
        component: 'view.comm_group',
        meta: {
          title: 'comm_group',
          i18nKey: 'route.comm_group'
        }
      },
      {
        name: 'comm_meeting',
        path: '/comm/meeting',
        component: 'view.comm_meeting',
        meta: {
          title: 'comm_meeting',
          i18nKey: 'route.comm_meeting'
        }
      },
      {
        name: 'comm_message',
        path: '/comm/message',
        component: 'view.comm_message',
        meta: {
          title: 'comm_message',
          i18nKey: 'route.comm_message'
        }
      },
      {
        name: 'comm_settings',
        path: '/comm/settings',
        component: 'view.comm_settings',
        meta: {
          title: 'comm_settings',
          i18nKey: 'route.comm_settings'
        }
      },
      {
        name: 'comm_todo',
        path: '/comm/todo',
        component: 'view.comm_todo',
        meta: {
          title: 'comm_todo',
          i18nKey: 'route.comm_todo'
        }
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_demo',
        path: '/demo/demo',
        component: 'view.demo_demo',
        meta: {
          title: 'demo_demo',
          i18nKey: 'route.demo_demo'
        }
      },
      {
        name: 'demo_tree',
        path: '/demo/tree',
        component: 'view.demo_tree',
        meta: {
          title: 'demo_tree',
          i18nKey: 'route.demo_tree'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iec',
    path: '/iec',
    component: 'layout.base',
    meta: {
      title: 'iec',
      i18nKey: 'route.iec'
    },
    children: [
      {
        name: 'iec_auto-flow',
        path: '/iec/auto-flow',
        component: 'view.iec_auto-flow',
        meta: {
          title: 'iec_auto-flow',
          i18nKey: 'route.iec_auto-flow'
        }
      },
      {
        name: 'iec_credential',
        path: '/iec/credential',
        component: 'view.iec_credential',
        meta: {
          title: 'iec_credential',
          i18nKey: 'route.iec_credential'
        }
      },
      {
        name: 'iec_dashboard',
        path: '/iec/dashboard',
        component: 'view.iec_dashboard',
        meta: {
          title: 'iec_dashboard',
          i18nKey: 'route.iec_dashboard'
        }
      },
      {
        name: 'iec_execution-log',
        path: '/iec/execution-log',
        component: 'view.iec_execution-log',
        meta: {
          title: 'iec_execution-log',
          i18nKey: 'route.iec_execution-log'
        }
      },
      {
        name: 'iec_performance',
        path: '/iec/performance',
        component: 'view.iec_performance',
        meta: {
          title: 'iec_performance',
          i18nKey: 'route.iec_performance'
        }
      },
      {
        name: 'iec_role-config',
        path: '/iec/role-config',
        component: 'view.iec_role-config',
        meta: {
          title: 'iec_role-config',
          i18nKey: 'route.iec_role-config'
        }
      },
      {
        name: 'iec_rpa',
        path: '/iec/rpa',
        component: 'view.iec_rpa',
        meta: {
          title: 'iec_rpa',
          i18nKey: 'route.iec_rpa'
        }
      },
      {
        name: 'iec_takeover',
        path: '/iec/takeover',
        component: 'view.iec_takeover',
        meta: {
          title: 'iec_takeover',
          i18nKey: 'route.iec_takeover'
        }
      },
      {
        name: 'iec_task-queue',
        path: '/iec/task-queue',
        component: 'view.iec_task-queue',
        meta: {
          title: 'iec_task-queue',
          i18nKey: 'route.iec_task-queue'
        }
      }
    ]
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'oms',
    path: '/oms',
    component: 'layout.base',
    meta: {
      title: 'oms',
      i18nKey: 'route.oms'
    },
    children: [
      {
        name: 'oms_approval-flow',
        path: '/oms/approval-flow',
        component: 'view.oms_approval-flow',
        meta: {
          title: 'oms_approval-flow',
          i18nKey: 'route.oms_approval-flow'
        }
      },
      {
        name: 'oms_business-rule',
        path: '/oms/business-rule',
        component: 'view.oms_business-rule',
        meta: {
          title: 'oms_business-rule',
          i18nKey: 'route.oms_business-rule'
        }
      },
      {
        name: 'oms_cargo-grouping-rule',
        path: '/oms/cargo-grouping-rule',
        component: 'view.oms_cargo-grouping-rule',
        meta: {
          title: 'oms_cargo-grouping-rule',
          i18nKey: 'route.oms_cargo-grouping-rule'
        }
      },
      {
        name: 'oms_cargo-order',
        path: '/oms/cargo-order',
        component: 'view.oms_cargo-order',
        meta: {
          title: 'oms_cargo-order',
          i18nKey: 'route.oms_cargo-order'
        }
      },
      {
        name: 'oms_container-order',
        path: '/oms/container-order',
        component: 'view.oms_container-order',
        meta: {
          title: 'oms_container-order',
          i18nKey: 'route.oms_container-order'
        }
      },
      {
        name: 'oms_inbound-plan',
        path: '/oms/inbound-plan',
        component: 'view.oms_inbound-plan',
        meta: {
          title: 'oms_inbound-plan',
          i18nKey: 'route.oms_inbound-plan'
        }
      },
      {
        name: 'oms_local-order',
        path: '/oms/local-order',
        component: 'view.oms_local-order',
        meta: {
          title: 'oms_local-order',
          i18nKey: 'route.oms_local-order'
        }
      },
      {
        name: 'oms_local-order-detail',
        path: '/oms/local-order-detail',
        component: 'view.oms_local-order-detail',
        meta: {
          title: 'oms_local-order-detail',
          i18nKey: 'route.oms_local-order-detail',
          hideInMenu: true,
          activeMenu: 'oms_local-order'
        }
      },
      {
        name: 'oms_ltl-order',
        path: '/oms/ltl-order',
        component: 'view.oms_ltl-order',
        meta: {
          title: 'oms_ltl-order',
          i18nKey: 'route.oms_ltl-order'
        }
      },
      {
        name: 'oms_ltl-order-detail',
        path: '/oms/ltl-order-detail',
        component: 'view.oms_ltl-order-detail',
        meta: {
          title: 'oms_ltl-order-detail',
          i18nKey: 'route.oms_ltl-order-detail',
          hideInMenu: true,
          activeMenu: 'oms_ltl-order'
        }
      },
      {
        name: 'oms_order-workbench',
        path: '/oms/order-workbench',
        component: 'view.oms_order-workbench',
        meta: {
          title: 'oms_order-workbench',
          i18nKey: 'route.oms_order-workbench'
        }
      },
      {
        name: 'oms_outbound-order',
        path: '/oms/outbound-order',
        component: 'view.oms_outbound-order',
        meta: {
          title: 'oms_outbound-order',
          i18nKey: 'route.oms_outbound-order'
        }
      },
      {
        name: 'oms_outbound-pool',
        path: '/oms/outbound-pool',
        component: 'view.oms_outbound-pool',
        meta: {
          title: 'oms_outbound-pool',
          i18nKey: 'route.oms_outbound-pool'
        }
      },
      {
        name: 'oms_platform-appointment',
        path: '/oms/platform-appointment',
        component: 'view.oms_platform-appointment',
        meta: {
          title: 'oms_platform-appointment',
          i18nKey: 'route.oms_platform-appointment'
        }
      },
      {
        name: 'oms_platform-order',
        path: '/oms/platform-order',
        component: 'view.oms_platform-order',
        meta: {
          title: 'oms_platform-order',
          i18nKey: 'route.oms_platform-order'
        }
      },
      {
        name: 'oms_platform-warehouse',
        path: '/oms/platform-warehouse',
        component: 'view.oms_platform-warehouse',
        meta: {
          title: 'oms_platform-warehouse',
          i18nKey: 'route.oms_platform-warehouse'
        }
      },
      {
        name: 'oms_pre-outbound',
        path: '/oms/pre-outbound',
        component: 'view.oms_pre-outbound',
        meta: {
          title: 'oms_pre-outbound',
          i18nKey: 'route.oms_pre-outbound'
        }
      },
      {
        name: 'oms_trip-order-detail',
        path: '/oms/trip-order-detail',
        component: 'view.oms_trip-order-detail',
        meta: {
          title: 'oms_trip-order-detail',
          i18nKey: 'route.oms_trip-order-detail'
        }
      },
      {
        name: 'oms_trip-recommend',
        path: '/oms/trip-recommend',
        component: 'view.oms_trip-recommend',
        meta: {
          title: 'oms_trip-recommend',
          i18nKey: 'route.oms_trip-recommend'
        }
      },
      {
        name: 'oms_zone-rule',
        path: '/oms/zone-rule',
        component: 'view.oms_zone-rule',
        meta: {
          title: 'oms_zone-rule',
          i18nKey: 'route.oms_zone-rule'
        }
      }
    ]
  },
  {
    name: 'pda',
    path: '/pda',
    component: 'layout.base',
    meta: {
      title: 'pda',
      i18nKey: 'route.pda'
    },
    children: [
      {
        name: 'pda_business',
        path: '/pda/business',
        component: 'view.pda_business',
        meta: {
          title: 'pda_business',
          i18nKey: 'route.pda_business',
          hideInMenu: true,
          activeMenu: 'pda_home'
        }
      },
      {
        name: 'pda_devanning',
        path: '/pda/devanning',
        component: 'view.pda_devanning',
        meta: {
          title: 'pda_devanning',
          i18nKey: 'route.pda_devanning',
          hideInMenu: true,
          activeMenu: 'pda_home'
        }
      },
      {
        name: 'pda_home',
        path: '/pda/home',
        component: 'view.pda_home',
        meta: {
          title: 'pda_home',
          i18nKey: 'route.pda_home'
        }
      },
      {
        name: 'pda_inbound',
        path: '/pda/inbound',
        component: 'view.pda_inbound',
        meta: {
          title: 'pda_inbound',
          i18nKey: 'route.pda_inbound',
          hideInMenu: true,
          activeMenu: 'pda_home'
        }
      },
      {
        name: 'pda_outbound',
        path: '/pda/outbound',
        component: 'view.pda_outbound',
        meta: {
          title: 'pda_outbound',
          i18nKey: 'route.pda_outbound',
          hideInMenu: true,
          activeMenu: 'pda_home'
        }
      },
      {
        name: 'pda_task',
        path: '/pda/task',
        component: 'view.pda_task',
        meta: {
          title: 'pda_task',
          i18nKey: 'route.pda_task'
        }
      }
    ]
  },
  {
    name: 'portal',
    path: '/portal',
    component: 'layout.base',
    meta: {
      title: 'portal',
      i18nKey: 'route.portal'
    },
    children: [
      {
        name: 'portal_bill',
        path: '/portal/bill',
        component: 'view.portal_bill',
        meta: {
          title: 'portal_bill',
          i18nKey: 'route.portal_bill'
        }
      },
      {
        name: 'portal_comm',
        path: '/portal/comm',
        component: 'view.portal_comm',
        meta: {
          title: 'portal_comm',
          i18nKey: 'route.portal_comm'
        }
      },
      {
        name: 'portal_containers',
        path: '/portal/containers',
        component: 'view.portal_containers',
        meta: {
          title: 'portal_containers',
          i18nKey: 'route.portal_containers'
        }
      },
      {
        name: 'portal_exception',
        path: '/portal/exception',
        component: 'view.portal_exception',
        meta: {
          title: 'portal_exception',
          i18nKey: 'route.portal_exception'
        }
      },
      {
        name: 'portal_fee-confirm',
        path: '/portal/fee-confirm',
        component: 'view.portal_fee-confirm',
        meta: {
          title: 'portal_fee-confirm',
          i18nKey: 'route.portal_fee-confirm'
        }
      },
      {
        name: 'portal_files',
        path: '/portal/files',
        component: 'view.portal_files',
        meta: {
          title: 'portal_files',
          i18nKey: 'route.portal_files'
        }
      },
      {
        name: 'portal_home',
        path: '/portal/home',
        component: 'view.portal_home',
        meta: {
          title: 'portal_home',
          i18nKey: 'route.portal_home'
        }
      },
      {
        name: 'portal_in-transit',
        path: '/portal/in-transit',
        component: 'view.portal_in-transit',
        meta: {
          title: 'portal_in-transit',
          i18nKey: 'route.portal_in-transit'
        }
      },
      {
        name: 'portal_inventory',
        path: '/portal/inventory',
        component: 'view.portal_inventory',
        meta: {
          title: 'portal_inventory',
          i18nKey: 'route.portal_inventory'
        }
      },
      {
        name: 'portal_order-create',
        path: '/portal/order-create',
        component: 'view.portal_order-create',
        meta: {
          title: 'portal_order-create',
          i18nKey: 'route.portal_order-create'
        }
      },
      {
        name: 'portal_orders',
        path: '/portal/orders',
        component: 'view.portal_orders',
        meta: {
          title: 'portal_orders',
          i18nKey: 'route.portal_orders'
        }
      },
      {
        name: 'portal_settings',
        path: '/portal/settings',
        component: 'view.portal_settings',
        meta: {
          title: 'portal_settings',
          i18nKey: 'route.portal_settings'
        }
      },
      {
        name: 'portal_transfer-ops',
        path: '/portal/transfer-ops',
        component: 'view.portal_transfer-ops',
        meta: {
          title: 'portal_transfer-ops',
          i18nKey: 'route.portal_transfer-ops'
        }
      }
    ]
  },
  {
    name: 'print',
    path: '/print',
    component: 'layout.base',
    meta: {
      title: 'print',
      i18nKey: 'route.print'
    },
    children: [
      {
        name: 'print_batch',
        path: '/print/batch',
        component: 'view.print_batch',
        meta: {
          title: 'print_batch',
          i18nKey: 'route.print_batch',
          hideInMenu: true
        }
      },
      {
        name: 'print_designer',
        path: '/print/designer',
        component: 'view.print_designer',
        meta: {
          title: 'print_designer',
          i18nKey: 'route.print_designer',
          hideInMenu: true,
          activeMenu: 'print_template-pallet-label'
        }
      },
      {
        name: 'print_permission',
        path: '/print/permission',
        component: 'view.print_permission',
        meta: {
          title: 'print_permission',
          i18nKey: 'route.print_permission'
        }
      },
      {
        name: 'print_printer',
        path: '/print/printer',
        component: 'view.print_printer',
        meta: {
          title: 'print_printer',
          i18nKey: 'route.print_printer',
          hideInMenu: true
        }
      },
      {
        name: 'print_record',
        path: '/print/record',
        component: 'view.print_record',
        meta: {
          title: 'print_record',
          i18nKey: 'route.print_record',
          hideInMenu: true
        }
      },
      {
        name: 'print_rule',
        path: '/print/rule',
        component: 'view.print_rule',
        meta: {
          title: 'print_rule',
          i18nKey: 'route.print_rule'
        }
      },
      {
        name: 'print_task',
        path: '/print/task',
        component: 'view.print_task',
        meta: {
          title: 'print_task',
          i18nKey: 'route.print_task',
          hideInMenu: true
        }
      },
      {
        name: 'print_template-bol',
        path: '/print/template-bol',
        component: 'view.print_template-bol',
        meta: {
          title: 'print_template-bol',
          i18nKey: 'route.print_template-bol'
        }
      },
      {
        name: 'print_template-carton',
        path: '/print/template-carton',
        component: 'view.print_template-carton',
        meta: {
          title: 'print_template-carton',
          i18nKey: 'route.print_template-carton'
        }
      },
      {
        name: 'print_template-custom',
        path: '/print/template-custom',
        component: 'view.print_template-custom',
        meta: {
          title: 'print_template-custom',
          i18nKey: 'route.print_template-custom'
        }
      },
      {
        name: 'print_template-devanning',
        path: '/print/template-devanning',
        component: 'view.print_template-devanning',
        meta: {
          title: 'print_template-devanning',
          i18nKey: 'route.print_template-devanning'
        }
      },
      {
        name: 'print_template-invoice',
        path: '/print/template-invoice',
        component: 'view.print_template-invoice',
        meta: {
          title: 'print_template-invoice',
          i18nKey: 'route.print_template-invoice'
        }
      },
      {
        name: 'print_template-location',
        path: '/print/template-location',
        component: 'view.print_template-location',
        meta: {
          title: 'print_template-location',
          i18nKey: 'route.print_template-location'
        }
      },
      {
        name: 'print_template-pallet-label',
        path: '/print/template-pallet-label',
        component: 'view.print_template-pallet-label',
        meta: {
          title: 'print_template-pallet-label',
          i18nKey: 'route.print_template-pallet-label'
        }
      },
      {
        name: 'print_template-report',
        path: '/print/template-report',
        component: 'view.print_template-report',
        meta: {
          title: 'print_template-report',
          i18nKey: 'route.print_template-report'
        }
      },
      {
        name: 'print_template-version',
        path: '/print/template-version',
        component: 'view.print_template-version',
        meta: {
          title: 'print_template-version',
          i18nKey: 'route.print_template-version'
        }
      },
      {
        name: 'print_workbench',
        path: '/print/workbench',
        component: 'view.print_workbench',
        meta: {
          title: 'print_workbench',
          i18nKey: 'route.print_workbench'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_theme-config',
        path: '/system/theme-config',
        component: 'view.system_theme-config',
        meta: {
          title: 'system_theme-config',
          i18nKey: 'route.system_theme-config'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tms',
    path: '/tms',
    component: 'layout.base',
    meta: {
      title: 'tms',
      i18nKey: 'route.tms'
    },
    children: [
      {
        name: 'tms_dispatch',
        path: '/tms/dispatch',
        component: 'view.tms_dispatch',
        meta: {
          title: 'tms_dispatch',
          i18nKey: 'route.tms_dispatch'
        }
      },
      {
        name: 'tms_dock-board',
        path: '/tms/dock-board',
        component: 'view.tms_dock-board',
        meta: {
          title: 'tms_dock-board',
          i18nKey: 'route.tms_dock-board'
        }
      },
      {
        name: 'tms_driver',
        path: '/tms/driver',
        component: 'view.tms_driver',
        meta: {
          title: 'tms_driver',
          i18nKey: 'route.tms_driver'
        }
      },
      {
        name: 'tms_exception',
        path: '/tms/exception',
        component: 'view.tms_exception',
        meta: {
          title: 'tms_exception',
          i18nKey: 'route.tms_exception'
        }
      },
      {
        name: 'tms_freight-settlement',
        path: '/tms/freight-settlement',
        component: 'view.tms_freight-settlement',
        meta: {
          title: 'tms_freight-settlement',
          i18nKey: 'route.tms_freight-settlement'
        }
      },
      {
        name: 'tms_home',
        path: '/tms/home',
        component: 'view.tms_home',
        meta: {
          title: 'tms_home',
          i18nKey: 'route.tms_home'
        }
      },
      {
        name: 'tms_log',
        path: '/tms/log',
        component: 'view.tms_log',
        meta: {
          title: 'tms_log',
          i18nKey: 'route.tms_log'
        }
      },
      {
        name: 'tms_pod',
        path: '/tms/pod',
        component: 'view.tms_pod',
        meta: {
          title: 'tms_pod',
          i18nKey: 'route.tms_pod'
        }
      },
      {
        name: 'tms_supplier',
        path: '/tms/supplier',
        meta: {
          title: 'tms_supplier',
          i18nKey: 'route.tms_supplier'
        },
        children: [
          {
            name: 'tms_supplier_account',
            path: '/tms/supplier/account',
            component: 'view.tms_supplier_account',
            meta: {
              title: 'tms_supplier_account',
              i18nKey: 'route.tms_supplier_account'
            }
          },
          {
            name: 'tms_supplier_bill',
            path: '/tms/supplier/bill',
            component: 'view.tms_supplier_bill',
            meta: {
              title: 'tms_supplier_bill',
              i18nKey: 'route.tms_supplier_bill'
            }
          },
          {
            name: 'tms_supplier_devanning-loading',
            path: '/tms/supplier/devanning-loading',
            component: 'view.tms_supplier_devanning-loading',
            meta: {
              title: 'tms_supplier_devanning-loading',
              i18nKey: 'route.tms_supplier_devanning-loading'
            }
          },
          {
            name: 'tms_supplier_drayage',
            path: '/tms/supplier/drayage',
            component: 'view.tms_supplier_drayage',
            meta: {
              title: 'tms_supplier_drayage',
              i18nKey: 'route.tms_supplier_drayage'
            }
          },
          {
            name: 'tms_supplier_fleet',
            path: '/tms/supplier/fleet',
            component: 'view.tms_supplier_fleet',
            meta: {
              title: 'tms_supplier_fleet',
              i18nKey: 'route.tms_supplier_fleet'
            }
          },
          {
            name: 'tms_supplier_kpi',
            path: '/tms/supplier/kpi',
            component: 'view.tms_supplier_kpi',
            meta: {
              title: 'tms_supplier_kpi',
              i18nKey: 'route.tms_supplier_kpi'
            }
          },
          {
            name: 'tms_supplier_linehaul',
            path: '/tms/supplier/linehaul',
            component: 'view.tms_supplier_linehaul',
            meta: {
              title: 'tms_supplier_linehaul',
              i18nKey: 'route.tms_supplier_linehaul'
            }
          },
          {
            name: 'tms_supplier_ltl',
            path: '/tms/supplier/ltl',
            component: 'view.tms_supplier_ltl',
            meta: {
              title: 'tms_supplier_ltl',
              i18nKey: 'route.tms_supplier_ltl'
            }
          },
          {
            name: 'tms_supplier_quote',
            path: '/tms/supplier/quote',
            component: 'view.tms_supplier_quote',
            meta: {
              title: 'tms_supplier_quote',
              i18nKey: 'route.tms_supplier_quote'
            }
          }
        ]
      },
      {
        name: 'tms_supplier-task',
        path: '/tms/supplier-task',
        component: 'view.tms_supplier-task',
        meta: {
          title: 'tms_supplier-task',
          i18nKey: 'route.tms_supplier-task'
        }
      },
      {
        name: 'tms_vehicle',
        path: '/tms/vehicle',
        component: 'view.tms_vehicle',
        meta: {
          title: 'tms_vehicle',
          i18nKey: 'route.tms_vehicle'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'wms',
    path: '/wms',
    component: 'layout.base',
    meta: {
      title: 'wms',
      i18nKey: 'route.wms',
      icon: 'mdi:package-variant-closed'
    },
    children: [
      {
        name: 'wms_bol-pod',
        path: '/wms/bol-pod',
        component: 'view.wms_bol-pod',
        meta: {
          title: 'wms_bol-pod',
          i18nKey: 'route.wms_bol-pod'
        }
      },
      {
        name: 'wms_devanning-dock-qr',
        path: '/wms/devanning-dock-qr',
        component: 'view.wms_devanning-dock-qr',
        meta: {
          title: 'wms_devanning-dock-qr',
          i18nKey: 'route.wms_devanning-dock-qr'
        }
      },
      {
        name: 'wms_devanning-order',
        path: '/wms/devanning-order',
        component: 'view.wms_devanning-order',
        meta: {
          title: 'wms_devanning-order',
          i18nKey: 'route.wms_devanning-order'
        }
      },
      {
        name: 'wms_devanning-order-detail',
        path: '/wms/devanning-order-detail',
        component: 'view.wms_devanning-order-detail',
        meta: {
          title: 'wms_devanning-order-detail',
          i18nKey: 'route.wms_devanning-order-detail',
          hideInMenu: true,
          activeMenu: 'wms_devanning-order',
          multiTab: true
        }
      },
      {
        name: 'wms_devanning-work',
        path: '/wms/devanning-work',
        component: 'view.wms_devanning-work',
        meta: {
          title: 'wms_devanning-work',
          i18nKey: 'route.wms_devanning-work'
        }
      },
      {
        name: 'wms_devanning-work-exec',
        path: '/wms/devanning-work-exec',
        component: 'view.wms_devanning-work-exec',
        meta: {
          title: 'wms_devanning-work-exec',
          i18nKey: 'route.wms_devanning-work-exec',
          hideInMenu: true,
          activeMenu: 'wms_devanning-work',
          multiTab: true
        }
      },
      {
        name: 'wms_dock-auto-schedule',
        path: '/wms/dock-auto-schedule',
        component: 'view.wms_dock-auto-schedule',
        meta: {
          title: 'wms_dock-auto-schedule',
          i18nKey: 'route.wms_dock-auto-schedule'
        }
      },
      {
        name: 'wms_driver-checkin',
        path: '/wms/driver-checkin',
        component: 'view.wms_driver-checkin',
        meta: {
          title: 'wms_driver-checkin',
          i18nKey: 'route.wms_driver-checkin'
        }
      },
      {
        name: 'wms_inventory',
        path: '/wms/inventory',
        component: 'view.wms_inventory',
        meta: {
          title: 'wms_inventory',
          i18nKey: 'route.wms_inventory'
        }
      },
      {
        name: 'wms_inventory-lock',
        path: '/wms/inventory-lock',
        component: 'view.wms_inventory-lock',
        meta: {
          title: 'wms_inventory-lock',
          i18nKey: 'route.wms_inventory-lock'
        }
      },
      {
        name: 'wms_inventory-transaction',
        path: '/wms/inventory-transaction',
        component: 'view.wms_inventory-transaction',
        meta: {
          title: 'wms_inventory-transaction',
          i18nKey: 'route.wms_inventory-transaction'
        }
      },
      {
        name: 'wms_inventory-visualization',
        path: '/wms/inventory-visualization',
        component: 'view.wms_inventory-visualization',
        meta: {
          title: 'wms_inventory-visualization',
          i18nKey: 'route.wms_inventory-visualization'
        }
      },
      {
        name: 'wms_location',
        path: '/wms/location',
        component: 'view.wms_location',
        meta: {
          title: 'wms_location',
          i18nKey: 'route.wms_location'
        }
      },
      {
        name: 'wms_operation-order',
        path: '/wms/operation-order',
        component: 'view.wms_operation-order',
        meta: {
          title: 'wms_operation-order',
          i18nKey: 'route.wms_operation-order'
        }
      },
      {
        name: 'wms_outbound-exec',
        path: '/wms/outbound-exec',
        component: 'view.wms_outbound-exec',
        meta: {
          title: 'wms_outbound-exec',
          i18nKey: 'route.wms_outbound-exec'
        }
      },
      {
        name: 'wms_outbound-loading',
        path: '/wms/outbound-loading',
        component: 'view.wms_outbound-loading',
        meta: {
          title: 'wms_outbound-loading',
          i18nKey: 'route.wms_outbound-loading'
        }
      },
      {
        name: 'wms_outbound-order',
        path: '/wms/outbound-order',
        component: 'view.wms_outbound-order',
        meta: {
          title: 'wms_outbound-order',
          i18nKey: 'route.wms_outbound-order'
        }
      },
      {
        name: 'wms_pallet',
        path: '/wms/pallet',
        component: 'view.wms_pallet',
        meta: {
          title: 'wms_pallet',
          i18nKey: 'route.wms_pallet'
        }
      },
      {
        name: 'wms_pallet-outbound',
        path: '/wms/pallet-outbound',
        component: 'view.wms_pallet-outbound',
        meta: {
          title: 'wms_pallet-outbound',
          i18nKey: 'route.wms_pallet-outbound'
        }
      },
      {
        name: 'wms_stock-prep-exec',
        path: '/wms/stock-prep-exec',
        component: 'view.wms_stock-prep-exec',
        meta: {
          title: 'wms_stock-prep-exec',
          i18nKey: 'route.wms_stock-prep-exec'
        }
      },
      {
        name: 'wms_stock-prep-order',
        path: '/wms/stock-prep-order',
        component: 'view.wms_stock-prep-order',
        meta: {
          title: 'wms_stock-prep-order',
          i18nKey: 'route.wms_stock-prep-order'
        }
      },
      {
        name: 'wms_stock-prep-task',
        path: '/wms/stock-prep-task',
        component: 'view.wms_stock-prep-task',
        meta: {
          title: 'wms_stock-prep-task',
          i18nKey: 'route.wms_stock-prep-task'
        }
      },
      {
        name: 'wms_transfer-workbench',
        path: '/wms/transfer-workbench',
        component: 'view.wms_transfer-workbench',
        meta: {
          title: 'wms_transfer-workbench',
          i18nKey: 'route.wms_transfer-workbench'
        }
      },
      {
        name: 'wms_trip-exception',
        path: '/wms/trip-exception',
        component: 'view.wms_trip-exception',
        meta: {
          title: 'wms_trip-exception',
          i18nKey: 'route.wms_trip-exception'
        }
      },
      {
        name: 'wms_trip-fee',
        path: '/wms/trip-fee',
        component: 'view.wms_trip-fee',
        meta: {
          title: 'wms_trip-fee',
          i18nKey: 'route.wms_trip-fee'
        }
      },
      {
        name: 'wms_trip-outbound-plan',
        path: '/wms/trip-outbound-plan',
        component: 'view.wms_trip-outbound-plan',
        meta: {
          title: 'wms_trip-outbound-plan',
          i18nKey: 'route.wms_trip-outbound-plan'
        }
      },
      {
        name: 'wms_vas-task',
        path: '/wms/vas-task',
        component: 'view.wms_vas-task',
        meta: {
          title: 'wms_vas-task',
          i18nKey: 'route.wms_vas-task'
        }
      },
      {
        name: 'wms_vas-work',
        path: '/wms/vas-work',
        component: 'view.wms_vas-work',
        meta: {
          title: 'wms_vas-work',
          i18nKey: 'route.wms_vas-work'
        }
      },
      {
        name: 'wms_zone',
        path: '/wms/zone',
        component: 'view.wms_zone',
        meta: {
          title: 'wms_zone',
          i18nKey: 'route.wms_zone'
        }
      }
    ]
  },
  {
    name: 'yard',
    path: '/yard',
    component: 'layout.base',
    meta: {
      title: 'yard',
      i18nKey: 'route.yard'
    },
    children: [
      {
        name: 'yard_dock',
        path: '/yard/dock',
        component: 'view.yard_dock',
        meta: {
          title: 'yard_dock',
          i18nKey: 'route.yard_dock'
        }
      },
      {
        name: 'yard_zone',
        path: '/yard/zone',
        component: 'view.yard_zone',
        meta: {
          title: 'yard_zone',
          i18nKey: 'route.yard_zone'
        }
      }
    ]
  },
  {
    name: 'yms',
    path: '/yms',
    component: 'layout.base',
    meta: {
      title: 'yms',
      i18nKey: 'route.yms'
    },
    children: [
      {
        name: 'yms_container',
        path: '/yms/container',
        component: 'view.yms_container',
        meta: {
          title: 'yms_container',
          i18nKey: 'route.yms_container'
        }
      },
      {
        name: 'yms_devanning',
        path: '/yms/devanning',
        component: 'view.yms_devanning',
        meta: {
          title: 'yms_devanning',
          i18nKey: 'route.yms_devanning'
        }
      },
      {
        name: 'yms_dispatch',
        path: '/yms/dispatch',
        component: 'view.yms_dispatch',
        meta: {
          title: 'yms_dispatch',
          i18nKey: 'route.yms_dispatch'
        }
      },
      {
        name: 'yms_dispatch-create',
        path: '/yms/dispatch-create',
        component: 'view.yms_dispatch-create',
        meta: {
          title: 'yms_dispatch-create',
          i18nKey: 'route.yms_dispatch-create'
        }
      },
      {
        name: 'yms_dispatch-detail',
        path: '/yms/dispatch-detail',
        component: 'view.yms_dispatch-detail',
        meta: {
          title: 'yms_dispatch-detail',
          i18nKey: 'route.yms_dispatch-detail'
        }
      },
      {
        name: 'yms_gate',
        path: '/yms/gate',
        component: 'view.yms_gate',
        meta: {
          title: 'yms_gate',
          i18nKey: 'route.yms_gate'
        }
      },
      {
        name: 'yms_gate-check-out',
        path: '/yms/gate-check-out',
        component: 'view.yms_gate-check-out',
        meta: {
          title: 'yms_gate-check-out',
          i18nKey: 'route.yms_gate-check-out'
        }
      },
      {
        name: 'yms_gate-checkin',
        path: '/yms/gate-checkin',
        component: 'view.yms_gate-checkin',
        meta: {
          title: 'yms_gate-checkin',
          i18nKey: 'route.yms_gate-checkin'
        }
      },
      {
        name: 'yms_gate-driver-qr',
        path: '/yms/gate-driver-qr',
        component: 'view.yms_gate-driver-qr',
        meta: {
          title: 'yms_gate-driver-qr',
          i18nKey: 'route.yms_gate-driver-qr'
        }
      },
      {
        name: 'yms_gate-in-yard',
        path: '/yms/gate-in-yard',
        component: 'view.yms_gate-in-yard',
        meta: {
          title: 'yms_gate-in-yard',
          i18nKey: 'route.yms_gate-in-yard'
        }
      },
      {
        name: 'yms_gate-trailer-link',
        path: '/yms/gate-trailer-link',
        component: 'view.yms_gate-trailer-link',
        meta: {
          title: 'yms_gate-trailer-link',
          i18nKey: 'route.yms_gate-trailer-link'
        }
      },
      {
        name: 'yms_h5-driver-checkin',
        path: '/yms/h5-driver-checkin',
        component: 'view.yms_h5-driver-checkin',
        meta: {
          title: 'yms_h5-driver-checkin',
          i18nKey: 'route.yms_h5-driver-checkin'
        }
      },
      {
        name: 'yms_h5-task-execute',
        path: '/yms/h5-task-execute',
        component: 'view.yms_h5-task-execute',
        meta: {
          title: 'yms_h5-task-execute',
          i18nKey: 'route.yms_h5-task-execute'
        }
      },
      {
        name: 'yms_h5-trailer-checkin',
        path: '/yms/h5-trailer-checkin',
        component: 'view.yms_h5-trailer-checkin',
        meta: {
          title: 'yms_h5-trailer-checkin',
          i18nKey: 'route.yms_h5-trailer-checkin'
        }
      },
      {
        name: 'yms_internal-task',
        path: '/yms/internal-task',
        component: 'view.yms_internal-task',
        meta: {
          title: 'yms_internal-task',
          i18nKey: 'route.yms_internal-task'
        }
      },
      {
        name: 'yms_loading',
        path: '/yms/loading',
        component: 'view.yms_loading',
        meta: {
          title: 'yms_loading',
          i18nKey: 'route.yms_loading'
        }
      },
      {
        name: 'yms_overview',
        path: '/yms/overview',
        component: 'view.yms_overview',
        meta: {
          title: 'yms_overview',
          i18nKey: 'route.yms_overview'
        }
      },
      {
        name: 'yms_task',
        path: '/yms/task',
        component: 'view.yms_task',
        meta: {
          title: 'yms_task',
          i18nKey: 'route.yms_task'
        }
      },
      {
        name: 'yms_trailer',
        path: '/yms/trailer',
        component: 'view.yms_trailer',
        meta: {
          title: 'yms_trailer',
          i18nKey: 'route.yms_trailer'
        }
      },
      {
        name: 'yms_yard-inventory',
        path: '/yms/yard-inventory',
        component: 'view.yms_yard-inventory',
        meta: {
          title: 'yms_yard-inventory',
          i18nKey: 'route.yms_yard-inventory'
        }
      },
      {
        name: 'yms_yard-position',
        path: '/yms/yard-position',
        component: 'view.yms_yard-position',
        meta: {
          title: 'yms_yard-position',
          i18nKey: 'route.yms_yard-position'
        }
      },
      {
        name: 'yms_zone',
        path: '/yms/zone',
        component: 'view.yms_zone',
        meta: {
          title: 'yms_zone',
          i18nKey: 'route.yms_zone'
        }
      }
    ]
  }
];
