/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'base',
    path: '/base',
    component: 'layout.base',
    meta: {
      title: 'base',
      i18nKey: 'route.base'
    },
    children: [
      {
        name: 'base_business-type',
        path: '/base/business-type',
        component: 'view.base_business-type',
        meta: {
          title: 'base_business-type',
          i18nKey: 'route.base_business-type'
        }
      },
      {
        name: 'base_channel',
        path: '/base/channel',
        component: 'view.base_channel',
        meta: {
          title: 'base_channel',
          i18nKey: 'route.base_channel'
        }
      },
      {
        name: 'base_city',
        path: '/base/city',
        component: 'view.base_city',
        meta: {
          title: 'base_city',
          i18nKey: 'route.base_city'
        }
      },
      {
        name: 'base_company',
        path: '/base/company',
        component: 'view.base_company',
        meta: {
          title: 'base_company',
          i18nKey: 'route.base_company'
        }
      },
      {
        name: 'base_country',
        path: '/base/country',
        component: 'view.base_country',
        meta: {
          title: 'base_country',
          i18nKey: 'route.base_country'
        }
      },
      {
        name: 'base_currency',
        path: '/base/currency',
        component: 'view.base_currency',
        meta: {
          title: 'base_currency',
          i18nKey: 'route.base_currency'
        }
      },
      {
        name: 'base_exchange-rate',
        path: '/base/exchange-rate',
        component: 'view.base_exchange-rate',
        meta: {
          title: 'base_exchange-rate',
          i18nKey: 'route.base_exchange-rate'
        }
      },
      {
        name: 'base_fee-item',
        path: '/base/fee-item',
        component: 'view.base_fee-item',
        meta: {
          title: 'base_fee-item',
          i18nKey: 'route.base_fee-item'
        }
      },
      {
        name: 'base_platform',
        path: '/base/platform',
        component: 'view.base_platform',
        meta: {
          title: 'base_platform',
          i18nKey: 'route.base_platform'
        }
      },
      {
        name: 'base_platform-address',
        path: '/base/platform-address',
        component: 'view.base_platform-address',
        meta: {
          title: 'base_platform-address',
          i18nKey: 'route.base_platform-address'
        }
      },
      {
        name: 'base_port',
        path: '/base/port',
        component: 'view.base_port',
        meta: {
          title: 'base_port',
          i18nKey: 'route.base_port'
        }
      },
      {
        name: 'base_shipping-line',
        path: '/base/shipping-line',
        component: 'view.base_shipping-line',
        meta: {
          title: 'base_shipping-line',
          i18nKey: 'route.base_shipping-line'
        }
      },
      {
        name: 'base_shipping-route',
        path: '/base/shipping-route',
        component: 'view.base_shipping-route',
        meta: {
          title: 'base_shipping-route',
          i18nKey: 'route.base_shipping-route'
        }
      },
      {
        name: 'base_sku',
        path: '/base/sku',
        component: 'view.base_sku',
        meta: {
          title: 'base_sku',
          i18nKey: 'route.base_sku'
        }
      },
      {
        name: 'base_state-province',
        path: '/base/state-province',
        component: 'view.base_state-province',
        meta: {
          title: 'base_state-province',
          i18nKey: 'route.base_state-province'
        }
      },
      {
        name: 'base_terminal',
        path: '/base/terminal',
        component: 'view.base_terminal',
        meta: {
          title: 'base_terminal',
          i18nKey: 'route.base_terminal'
        }
      },
      {
        name: 'base_timezone',
        path: '/base/timezone',
        component: 'view.base_timezone',
        meta: {
          title: 'base_timezone',
          i18nKey: 'route.base_timezone'
        }
      },
      {
        name: 'base_value-added-service',
        path: '/base/value-added-service',
        component: 'view.base_value-added-service',
        meta: {
          title: 'base_value-added-service',
          i18nKey: 'route.base_value-added-service'
        }
      },
      {
        name: 'base_vessel',
        path: '/base/vessel',
        component: 'view.base_vessel',
        meta: {
          title: 'base_vessel',
          i18nKey: 'route.base_vessel'
        }
      },
      {
        name: 'base_warehouse',
        path: '/base/warehouse',
        component: 'view.base_warehouse',
        meta: {
          title: 'base_warehouse',
          i18nKey: 'route.base_warehouse'
        }
      },
      {
        name: 'base_zip-code',
        path: '/base/zip-code',
        component: 'view.base_zip-code',
        meta: {
          title: 'base_zip-code',
          i18nKey: 'route.base_zip-code'
        }
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_demo',
        path: '/demo/demo',
        component: 'view.demo_demo',
        meta: {
          title: 'demo_demo',
          i18nKey: 'route.demo_demo'
        }
      },
      {
        name: 'demo_tree',
        path: '/demo/tree',
        component: 'view.demo_tree',
        meta: {
          title: 'demo_tree',
          i18nKey: 'route.demo_tree'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'oms',
    path: '/oms',
    component: 'layout.base',
    meta: {
      title: 'oms',
      i18nKey: 'route.oms'
    },
    children: [
      {
        name: 'oms_cargo-grouping-rule',
        path: '/oms/cargo-grouping-rule',
        component: 'view.oms_cargo-grouping-rule',
        meta: {
          title: 'oms_cargo-grouping-rule',
          i18nKey: 'route.oms_cargo-grouping-rule'
        }
      },
      {
        name: 'oms_cargo-order',
        path: '/oms/cargo-order',
        component: 'view.oms_cargo-order',
        meta: {
          title: 'oms_cargo-order',
          i18nKey: 'route.oms_cargo-order'
        }
      },
      {
        name: 'oms_container-order',
        path: '/oms/container-order',
        component: 'view.oms_container-order',
        meta: {
          title: 'oms_container-order',
          i18nKey: 'route.oms_container-order'
        }
      },
      {
        name: 'oms_inbound-plan',
        path: '/oms/inbound-plan',
        component: 'view.oms_inbound-plan',
        meta: {
          title: 'oms_inbound-plan',
          i18nKey: 'route.oms_inbound-plan'
        }
      },
      {
        name: 'oms_outbound-order',
        path: '/oms/outbound-order',
        component: 'view.oms_outbound-order',
        meta: {
          title: 'oms_outbound-order',
          i18nKey: 'route.oms_outbound-order'
        }
      },
      {
        name: 'oms_outbound-pool',
        path: '/oms/outbound-pool',
        component: 'view.oms_outbound-pool',
        meta: {
          title: 'oms_outbound-pool',
          i18nKey: 'route.oms_outbound-pool'
        }
      },
      {
        name: 'oms_pre-outbound',
        path: '/oms/pre-outbound',
        component: 'view.oms_pre-outbound',
        meta: {
          title: 'oms_pre-outbound',
          i18nKey: 'route.oms_pre-outbound'
        }
      }
    ]
  },
  {
    name: 'pda',
    path: '/pda',
    component: 'layout.base',
    meta: {
      title: 'pda',
      i18nKey: 'route.pda'
    },
    children: [
      {
        name: 'pda_home',
        path: '/pda/home',
        component: 'view.pda_home',
        meta: {
          title: 'pda_home',
          i18nKey: 'route.pda_home'
        }
      },
      {
        name: 'pda_task',
        path: '/pda/task',
        component: 'view.pda_task',
        meta: {
          title: 'pda_task',
          i18nKey: 'route.pda_task'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'wms',
    path: '/wms',
    component: 'layout.base',
    meta: {
      title: 'wms',
      i18nKey: 'route.wms'
    },
    children: [
      {
        name: 'wms_devanning-dock-qr',
        path: '/wms/devanning-dock-qr',
        component: 'view.wms_devanning-dock-qr',
        meta: {
          title: 'wms_devanning-dock-qr',
          i18nKey: 'route.wms_devanning-dock-qr'
        }
      },
      {
        name: 'wms_devanning-order',
        path: '/wms/devanning-order',
        component: 'view.wms_devanning-order',
        meta: {
          title: 'wms_devanning-order',
          i18nKey: 'route.wms_devanning-order'
        }
      },
      {
        name: 'wms_devanning-order-detail',
        path: '/wms/devanning-order-detail',
        component: 'view.wms_devanning-order-detail',
        meta: {
          title: 'wms_devanning-order-detail',
          i18nKey: 'route.wms_devanning-order-detail',
          hideInMenu: true,
          activeMenu: 'wms_devanning-order',
          multiTab: true
        }
      },
      {
        name: 'wms_devanning-work',
        path: '/wms/devanning-work',
        component: 'view.wms_devanning-work',
        meta: {
          title: 'wms_devanning-work',
          i18nKey: 'route.wms_devanning-work'
        }
      },
      {
        name: 'wms_devanning-work-exec',
        path: '/wms/devanning-work/execute',
        component: 'view.wms_devanning-work-exec',
        meta: {
          title: 'wms_devanning-work-exec',
          i18nKey: 'route.wms_devanning-work-exec',
          hideInMenu: true,
          activeMenu: 'wms_devanning-work',
          multiTab: true
        }
      },
      {
        name: 'wms_inbound-order',
        path: '/wms/inbound-order',
        component: 'view.wms_inbound-order',
        meta: {
          title: 'wms_inbound-order',
          i18nKey: 'route.wms_inbound-order'
        }
      },
      {
        name: 'wms_inbound-task',
        path: '/wms/inbound-task',
        component: 'view.wms_inbound-task',
        meta: {
          title: 'wms_inbound-task',
          i18nKey: 'route.wms_inbound-task'
        }
      },
      {
        name: 'wms_inventory',
        path: '/wms/inventory',
        component: 'view.wms_inventory',
        meta: {
          title: 'wms_inventory',
          i18nKey: 'route.wms_inventory'
        }
      },
      {
        name: 'wms_inventory-lock',
        path: '/wms/inventory-lock',
        component: 'view.wms_inventory-lock',
        meta: {
          title: 'wms_inventory-lock',
          i18nKey: 'route.wms_inventory-lock'
        }
      },
      {
        name: 'wms_inventory-transaction',
        path: '/wms/inventory-transaction',
        component: 'view.wms_inventory-transaction',
        meta: {
          title: 'wms_inventory-transaction',
          i18nKey: 'route.wms_inventory-transaction'
        }
      },
      {
        name: 'wms_inventory-visualization',
        path: '/wms/inventory-visualization',
        component: 'view.wms_inventory-visualization',
        meta: {
          title: 'wms_inventory-visualization',
          i18nKey: 'route.wms_inventory-visualization'
        }
      },
      {
        name: 'wms_location',
        path: '/wms/location',
        component: 'view.wms_location',
        meta: {
          title: 'wms_location',
          i18nKey: 'route.wms_location'
        }
      },
      {
        name: 'wms_operation-order',
        path: '/wms/operation-order',
        component: 'view.wms_operation-order',
        meta: {
          title: 'wms_operation-order',
          i18nKey: 'route.wms_operation-order'
        }
      },
      {
        name: 'wms_outbound-exec',
        path: '/wms/outbound-exec',
        component: 'view.wms_outbound-exec',
        meta: {
          title: 'wms_outbound-exec',
          i18nKey: 'route.wms_outbound-exec'
        }
      },
      {
        name: 'wms_outbound-loading',
        path: '/wms/outbound-loading',
        component: 'view.wms_outbound-loading',
        meta: {
          title: 'wms_outbound-loading',
          i18nKey: 'route.wms_outbound-loading'
        }
      },
      {
        name: 'wms_outbound-order',
        path: '/wms/outbound-order',
        component: 'view.wms_outbound-order',
        meta: {
          title: 'wms_outbound-order',
          i18nKey: 'route.wms_outbound-order'
        }
      },
      {
        name: 'wms_pallet',
        path: '/wms/pallet',
        component: 'view.wms_pallet',
        meta: {
          title: 'wms_pallet',
          i18nKey: 'route.wms_pallet'
        }
      },
      {
        name: 'wms_pallet-outbound',
        path: '/wms/pallet-outbound',
        component: 'view.wms_pallet-outbound',
        meta: {
          title: 'wms_pallet-outbound',
          i18nKey: 'route.wms_pallet-outbound'
        }
      },
      {
        name: 'wms_putaway-pda',
        path: '/wms/putaway-pda',
        component: 'view.wms_putaway-pda',
        meta: {
          title: 'wms_putaway-pda',
          i18nKey: 'route.wms_putaway-pda'
        }
      },
      {
        name: 'wms_putaway-task',
        path: '/wms/putaway-task',
        component: 'view.wms_putaway-task',
        meta: {
          title: 'wms_putaway-task',
          i18nKey: 'route.wms_putaway-task'
        }
      },
      {
        name: 'wms_stock-prep-exec',
        path: '/wms/stock-prep-exec',
        component: 'view.wms_stock-prep-exec',
        meta: {
          title: 'wms_stock-prep-exec',
          i18nKey: 'route.wms_stock-prep-exec'
        }
      },
      {
        name: 'wms_stock-prep-order',
        path: '/wms/stock-prep-order',
        component: 'view.wms_stock-prep-order',
        meta: {
          title: 'wms_stock-prep-order',
          i18nKey: 'route.wms_stock-prep-order'
        }
      },
      {
        name: 'wms_stock-prep-task',
        path: '/wms/stock-prep-task',
        component: 'view.wms_stock-prep-task',
        meta: {
          title: 'wms_stock-prep-task',
          i18nKey: 'route.wms_stock-prep-task'
        }
      },
      {
        name: 'wms_vas-task',
        path: '/wms/vas-task',
        component: 'view.wms_vas-task',
        meta: {
          title: 'wms_vas-task',
          i18nKey: 'route.wms_vas-task'
        }
      },
      {
        name: 'wms_vas-work',
        path: '/wms/vas-work',
        component: 'view.wms_vas-work',
        meta: {
          title: 'wms_vas-work',
          i18nKey: 'route.wms_vas-work'
        }
      },
      {
        name: 'wms_zone',
        path: '/wms/zone',
        component: 'view.wms_zone',
        meta: {
          title: 'wms_zone',
          i18nKey: 'route.wms_zone'
        }
      }
    ]
  },
  {
    name: 'yard',
    path: '/yard',
    component: 'layout.base',
    meta: {
      title: 'yard',
      i18nKey: 'route.yard'
    },
    children: [
      {
        name: 'yard_dock',
        path: '/yard/dock',
        component: 'view.yard_dock',
        meta: {
          title: 'yard_dock',
          i18nKey: 'route.yard_dock'
        }
      },
      {
        name: 'yard_zone',
        path: '/yard/zone',
        component: 'view.yard_zone',
        meta: {
          title: 'yard_zone',
          i18nKey: 'route.yard_zone'
        }
      }
    ]
  },
  {
    name: 'yms',
    path: '/yms',
    component: 'layout.base',
    meta: {
      title: 'yms',
      i18nKey: 'route.yms'
    },
    children: [
      {
        name: 'yms_container',
        path: '/yms/container',
        component: 'view.yms_container',
        meta: {
          title: 'yms_container',
          i18nKey: 'route.yms_container'
        }
      },
      {
        name: 'yms_devanning',
        path: '/yms/devanning',
        component: 'view.yms_devanning',
        meta: {
          title: 'yms_devanning',
          i18nKey: 'route.yms_devanning'
        }
      },
      {
        name: 'yms_dispatch',
        path: '/yms/dispatch',
        component: 'view.yms_dispatch',
        meta: {
          title: 'yms_dispatch',
          i18nKey: 'route.yms_dispatch'
        }
      },
      {
        name: 'yms_dispatch-create',
        path: '/yms/dispatch-create',
        component: 'view.yms_dispatch-create',
        meta: {
          title: 'yms_dispatch-create',
          i18nKey: 'route.yms_dispatch-create'
        }
      },
      {
        name: 'yms_dispatch-detail',
        path: '/yms/dispatch-detail',
        component: 'view.yms_dispatch-detail',
        meta: {
          title: 'yms_dispatch-detail',
          i18nKey: 'route.yms_dispatch-detail'
        }
      },
      {
        name: 'yms_gate',
        path: '/yms/gate',
        component: 'view.yms_gate',
        meta: {
          title: 'yms_gate',
          i18nKey: 'route.yms_gate'
        }
      },
      {
        name: 'yms_gate-check-out',
        path: '/yms/gate-check-out',
        component: 'view.yms_gate-check-out',
        meta: {
          title: 'yms_gate-check-out',
          i18nKey: 'route.yms_gate-check-out'
        }
      },
      {
        name: 'yms_gate-checkin',
        path: '/yms/gate-checkin',
        component: 'view.yms_gate-checkin',
        meta: {
          title: 'yms_gate-checkin',
          i18nKey: 'route.yms_gate-checkin'
        }
      },
      {
        name: 'yms_gate-driver-qr',
        path: '/yms/gate-driver-qr',
        component: 'view.yms_gate-driver-qr',
        meta: {
          title: 'yms_gate-driver-qr',
          i18nKey: 'route.yms_gate-driver-qr'
        }
      },
      {
        name: 'yms_gate-in-yard',
        path: '/yms/gate-in-yard',
        component: 'view.yms_gate-in-yard',
        meta: {
          title: 'yms_gate-in-yard',
          i18nKey: 'route.yms_gate-in-yard'
        }
      },
      {
        name: 'yms_gate-trailer-link',
        path: '/yms/gate-trailer-link',
        component: 'view.yms_gate-trailer-link',
        meta: {
          title: 'yms_gate-trailer-link',
          i18nKey: 'route.yms_gate-trailer-link'
        }
      },
      {
        name: 'yms_h5-driver-checkin',
        path: '/yms/h5-driver-checkin',
        component: 'view.yms_h5-driver-checkin',
        meta: {
          title: 'yms_h5-driver-checkin',
          i18nKey: 'route.yms_h5-driver-checkin'
        }
      },
      {
        name: 'yms_h5-task-execute',
        path: '/yms/h5-task-execute',
        component: 'view.yms_h5-task-execute',
        meta: {
          title: 'yms_h5-task-execute',
          i18nKey: 'route.yms_h5-task-execute'
        }
      },
      {
        name: 'yms_h5-trailer-checkin',
        path: '/yms/h5-trailer-checkin',
        component: 'view.yms_h5-trailer-checkin',
        meta: {
          title: 'yms_h5-trailer-checkin',
          i18nKey: 'route.yms_h5-trailer-checkin'
        }
      },
      {
        name: 'yms_internal-task',
        path: '/yms/internal-task',
        component: 'view.yms_internal-task',
        meta: {
          title: 'yms_internal-task',
          i18nKey: 'route.yms_internal-task'
        }
      },
      {
        name: 'yms_loading',
        path: '/yms/loading',
        component: 'view.yms_loading',
        meta: {
          title: 'yms_loading',
          i18nKey: 'route.yms_loading'
        }
      },
      {
        name: 'yms_overview',
        path: '/yms/overview',
        component: 'view.yms_overview',
        meta: {
          title: 'yms_overview',
          i18nKey: 'route.yms_overview'
        }
      },
      {
        name: 'yms_task',
        path: '/yms/task',
        component: 'view.yms_task',
        meta: {
          title: 'yms_task',
          i18nKey: 'route.yms_task'
        }
      },
      {
        name: 'yms_trailer',
        path: '/yms/trailer',
        component: 'view.yms_trailer',
        meta: {
          title: 'yms_trailer',
          i18nKey: 'route.yms_trailer'
        }
      },
      {
        name: 'yms_yard-inventory',
        path: '/yms/yard-inventory',
        component: 'view.yms_yard-inventory',
        meta: {
          title: 'yms_yard-inventory',
          i18nKey: 'route.yms_yard-inventory'
        }
      },
      {
        name: 'yms_yard-position',
        path: '/yms/yard-position',
        component: 'view.yms_yard-position',
        meta: {
          title: 'yms_yard-position',
          i18nKey: 'route.yms_yard-position'
        }
      },
      {
        name: 'yms_zone',
        path: '/yms/zone',
        component: 'view.yms_zone',
        meta: {
          title: 'yms_zone',
          i18nKey: 'route.yms_zone'
        }
      }
    ]
  }
];
