/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "about": "/about",
  "base": "/base",
  "base_business-type": "/base/business-type",
  "base_channel": "/base/channel",
  "base_city": "/base/city",
  "base_company": "/base/company",
  "base_country": "/base/country",
  "base_currency": "/base/currency",
  "base_exchange-rate": "/base/exchange-rate",
  "base_fee-item": "/base/fee-item",
  "base_platform": "/base/platform",
  "base_platform-address": "/base/platform-address",
  "base_port": "/base/port",
  "base_shipping-line": "/base/shipping-line",
  "base_shipping-route": "/base/shipping-route",
  "base_sku": "/base/sku",
  "base_state-province": "/base/state-province",
  "base_terminal": "/base/terminal",
  "base_timezone": "/base/timezone",
  "base_value-added-service": "/base/value-added-service",
  "base_vessel": "/base/vessel",
  "base_warehouse": "/base/warehouse",
  "base_zip-code": "/base/zip-code",
  "demo": "/demo",
  "demo_demo": "/demo/demo",
  "demo_tree": "/demo/tree",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "monitor": "/monitor",
  "monitor_cache": "/monitor/cache",
  "monitor_logininfor": "/monitor/logininfor",
  "monitor_online": "/monitor/online",
  "monitor_operlog": "/monitor/operlog",
  "oms": "/oms",
  "oms_cargo-grouping-rule": "/oms/cargo-grouping-rule",
  "oms_cargo-order": "/oms/cargo-order",
  "oms_container-order": "/oms/container-order",
  "oms_inbound-plan": "/oms/inbound-plan",
  "oms_outbound-order": "/oms/outbound-order",
  "oms_outbound-pool": "/oms/outbound-pool",
  "oms_pre-outbound": "/oms/pre-outbound",
  "pda": "/pda",
  "pda_home": "/pda/home",
  "pda_task": "/pda/task",
  "social-callback": "/social-callback",
  "system": "/system",
  "system_client": "/system/client",
  "system_config": "/system/config",
  "system_dept": "/system/dept",
  "system_dict": "/system/dict",
  "system_menu": "/system/menu",
  "system_notice": "/system/notice",
  "system_oss": "/system/oss",
  "system_oss-config": "/system/oss-config",
  "system_post": "/system/post",
  "system_role": "/system/role",
  "system_tenant": "/system/tenant",
  "system_tenant-package": "/system/tenant-package",
  "system_user": "/system/user",
  "tool": "/tool",
  "tool_gen": "/tool/gen",
  "user-center": "/user-center",
  "wms": "/wms",
  "wms_devanning-dock-qr": "/wms/devanning-dock-qr",
  "wms_devanning-order": "/wms/devanning-order",
  "wms_devanning-order-detail": "/wms/devanning-order-detail",
  "wms_devanning-work": "/wms/devanning-work",
  "wms_devanning-work-exec": "/wms/devanning-work/execute",
  "wms_inbound-order": "/wms/inbound-order",
  "wms_inbound-task": "/wms/inbound-task",
  "wms_inventory": "/wms/inventory",
  "wms_inventory-lock": "/wms/inventory-lock",
  "wms_inventory-transaction": "/wms/inventory-transaction",
  "wms_inventory-visualization": "/wms/inventory-visualization",
  "wms_location": "/wms/location",
  "wms_operation-order": "/wms/operation-order",
  "wms_outbound-exec": "/wms/outbound-exec",
  "wms_outbound-loading": "/wms/outbound-loading",
  "wms_outbound-order": "/wms/outbound-order",
  "wms_pallet": "/wms/pallet",
  "wms_pallet-outbound": "/wms/pallet-outbound",
  "wms_putaway-pda": "/wms/putaway-pda",
  "wms_putaway-task": "/wms/putaway-task",
  "wms_stock-prep-exec": "/wms/stock-prep-exec",
  "wms_stock-prep-order": "/wms/stock-prep-order",
  "wms_stock-prep-task": "/wms/stock-prep-task",
  "wms_vas-task": "/wms/vas-task",
  "wms_vas-work": "/wms/vas-work",
  "wms_zone": "/wms/zone",
  "yard": "/yard",
  "yard_dock": "/yard/dock",
  "yard_zone": "/yard/zone",
  "yms": "/yms",
  "yms_container": "/yms/container",
  "yms_devanning": "/yms/devanning",
  "yms_dispatch": "/yms/dispatch",
  "yms_dispatch-create": "/yms/dispatch-create",
  "yms_dispatch-detail": "/yms/dispatch-detail",
  "yms_gate": "/yms/gate",
  "yms_gate-check-out": "/yms/gate-check-out",
  "yms_gate-checkin": "/yms/gate-checkin",
  "yms_gate-driver-qr": "/yms/gate-driver-qr",
  "yms_gate-in-yard": "/yms/gate-in-yard",
  "yms_gate-trailer-link": "/yms/gate-trailer-link",
  "yms_h5-driver-checkin": "/yms/h5-driver-checkin",
  "yms_h5-task-execute": "/yms/h5-task-execute",
  "yms_h5-trailer-checkin": "/yms/h5-trailer-checkin",
  "yms_internal-task": "/yms/internal-task",
  "yms_loading": "/yms/loading",
  "yms_overview": "/yms/overview",
  "yms_task": "/yms/task",
  "yms_trailer": "/yms/trailer",
  "yms_yard-inventory": "/yms/yard-inventory",
  "yms_yard-position": "/yms/yard-position",
  "yms_zone": "/yms/zone"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
