/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "base": "/base";
    "base_business-type": "/base/business-type";
    "base_channel": "/base/channel";
    "base_city": "/base/city";
    "base_company": "/base/company";
    "base_country": "/base/country";
    "base_currency": "/base/currency";
    "base_exchange-rate": "/base/exchange-rate";
    "base_fee-item": "/base/fee-item";
    "base_platform": "/base/platform";
    "base_platform-address": "/base/platform-address";
    "base_port": "/base/port";
    "base_shipping-line": "/base/shipping-line";
    "base_shipping-route": "/base/shipping-route";
    "base_sku": "/base/sku";
    "base_state-province": "/base/state-province";
    "base_terminal": "/base/terminal";
    "base_timezone": "/base/timezone";
    "base_value-added-service": "/base/value-added-service";
    "base_vessel": "/base/vessel";
    "base_warehouse": "/base/warehouse";
    "base_zip-code": "/base/zip-code";
    "demo": "/demo";
    "demo_demo": "/demo/demo";
    "demo_tree": "/demo/tree";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "monitor": "/monitor";
    "monitor_cache": "/monitor/cache";
    "monitor_logininfor": "/monitor/logininfor";
    "monitor_online": "/monitor/online";
    "monitor_operlog": "/monitor/operlog";
    "oms": "/oms";
    "oms_cargo-grouping-rule": "/oms/cargo-grouping-rule";
    "oms_cargo-order": "/oms/cargo-order";
    "oms_container-order": "/oms/container-order";
    "oms_inbound-plan": "/oms/inbound-plan";
    "oms_outbound-order": "/oms/outbound-order";
    "oms_outbound-pool": "/oms/outbound-pool";
    "oms_pre-outbound": "/oms/pre-outbound";
    "pda": "/pda";
    "pda_home": "/pda/home";
    "pda_task": "/pda/task";
    "social-callback": "/social-callback";
    "system": "/system";
    "system_client": "/system/client";
    "system_config": "/system/config";
    "system_dept": "/system/dept";
    "system_dict": "/system/dict";
    "system_menu": "/system/menu";
    "system_notice": "/system/notice";
    "system_oss": "/system/oss";
    "system_oss-config": "/system/oss-config";
    "system_post": "/system/post";
    "system_role": "/system/role";
    "system_tenant": "/system/tenant";
    "system_tenant-package": "/system/tenant-package";
    "system_user": "/system/user";
    "tool": "/tool";
    "tool_gen": "/tool/gen";
    "user-center": "/user-center";
    "wms": "/wms";
    "wms_devanning-dock-qr": "/wms/devanning-dock-qr";
    "wms_devanning-order": "/wms/devanning-order";
    "wms_devanning-order-detail": "/wms/devanning-order-detail";
    "wms_devanning-work": "/wms/devanning-work";
    "wms_devanning-work-exec": "/wms/devanning-work/execute";
    "wms_inbound-order": "/wms/inbound-order";
    "wms_inbound-task": "/wms/inbound-task";
    "wms_inventory": "/wms/inventory";
    "wms_inventory-lock": "/wms/inventory-lock";
    "wms_inventory-transaction": "/wms/inventory-transaction";
    "wms_inventory-visualization": "/wms/inventory-visualization";
    "wms_location": "/wms/location";
    "wms_operation-order": "/wms/operation-order";
    "wms_outbound-exec": "/wms/outbound-exec";
    "wms_outbound-loading": "/wms/outbound-loading";
    "wms_outbound-order": "/wms/outbound-order";
    "wms_pallet": "/wms/pallet";
    "wms_pallet-outbound": "/wms/pallet-outbound";
    "wms_putaway-pda": "/wms/putaway-pda";
    "wms_putaway-task": "/wms/putaway-task";
    "wms_stock-prep-exec": "/wms/stock-prep-exec";
    "wms_stock-prep-order": "/wms/stock-prep-order";
    "wms_stock-prep-task": "/wms/stock-prep-task";
    "wms_vas-task": "/wms/vas-task";
    "wms_vas-work": "/wms/vas-work";
    "wms_zone": "/wms/zone";
    "yard": "/yard";
    "yard_dock": "/yard/dock";
    "yard_zone": "/yard/zone";
    "yms": "/yms";
    "yms_container": "/yms/container";
    "yms_devanning": "/yms/devanning";
    "yms_dispatch": "/yms/dispatch";
    "yms_dispatch-create": "/yms/dispatch-create";
    "yms_dispatch-detail": "/yms/dispatch-detail";
    "yms_gate": "/yms/gate";
    "yms_gate-check-out": "/yms/gate-check-out";
    "yms_gate-checkin": "/yms/gate-checkin";
    "yms_gate-driver-qr": "/yms/gate-driver-qr";
    "yms_gate-in-yard": "/yms/gate-in-yard";
    "yms_gate-trailer-link": "/yms/gate-trailer-link";
    "yms_h5-driver-checkin": "/yms/h5-driver-checkin";
    "yms_h5-task-execute": "/yms/h5-task-execute";
    "yms_h5-trailer-checkin": "/yms/h5-trailer-checkin";
    "yms_internal-task": "/yms/internal-task";
    "yms_loading": "/yms/loading";
    "yms_overview": "/yms/overview";
    "yms_task": "/yms/task";
    "yms_trailer": "/yms/trailer";
    "yms_yard-inventory": "/yms/yard-inventory";
    "yms_yard-position": "/yms/yard-position";
    "yms_zone": "/yms/zone";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "base"
    | "demo"
    | "home"
    | "iframe-page"
    | "login"
    | "monitor"
    | "oms"
    | "pda"
    | "social-callback"
    | "system"
    | "tool"
    | "user-center"
    | "wms"
    | "yard"
    | "yms"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "social-callback"
    | "user-center"
    | "about"
    | "base_business-type"
    | "base_channel"
    | "base_city"
    | "base_company"
    | "base_country"
    | "base_currency"
    | "base_exchange-rate"
    | "base_fee-item"
    | "base_platform-address"
    | "base_platform"
    | "base_port"
    | "base_shipping-line"
    | "base_shipping-route"
    | "base_sku"
    | "base_state-province"
    | "base_terminal"
    | "base_timezone"
    | "base_value-added-service"
    | "base_vessel"
    | "base_warehouse"
    | "base_zip-code"
    | "demo_demo"
    | "demo_tree"
    | "home"
    | "monitor_cache"
    | "monitor_logininfor"
    | "monitor_online"
    | "monitor_operlog"
    | "oms_cargo-grouping-rule"
    | "oms_cargo-order"
    | "oms_container-order"
    | "oms_inbound-plan"
    | "oms_outbound-order"
    | "oms_outbound-pool"
    | "oms_pre-outbound"
    | "pda_home"
    | "pda_task"
    | "system_client"
    | "system_config"
    | "system_dept"
    | "system_dict"
    | "system_menu"
    | "system_notice"
    | "system_oss-config"
    | "system_oss"
    | "system_post"
    | "system_role"
    | "system_tenant-package"
    | "system_tenant"
    | "system_user"
    | "tool_gen"
    | "wms_devanning-dock-qr"
    | "wms_devanning-order-detail"
    | "wms_devanning-order"
    | "wms_devanning-work"
    | "wms_devanning-work-exec"
    | "wms_inbound-order"
    | "wms_inbound-task"
    | "wms_inventory-lock"
    | "wms_inventory-transaction"
    | "wms_inventory-visualization"
    | "wms_inventory"
    | "wms_location"
    | "wms_operation-order"
    | "wms_outbound-exec"
    | "wms_outbound-loading"
    | "wms_outbound-order"
    | "wms_pallet-outbound"
    | "wms_pallet"
    | "wms_putaway-pda"
    | "wms_putaway-task"
    | "wms_stock-prep-exec"
    | "wms_stock-prep-order"
    | "wms_stock-prep-task"
    | "wms_vas-task"
    | "wms_vas-work"
    | "wms_zone"
    | "yard_dock"
    | "yard_zone"
    | "yms_container"
    | "yms_devanning"
    | "yms_dispatch-create"
    | "yms_dispatch-detail"
    | "yms_dispatch"
    | "yms_gate-check-out"
    | "yms_gate-checkin"
    | "yms_gate-driver-qr"
    | "yms_gate-in-yard"
    | "yms_gate-trailer-link"
    | "yms_gate"
    | "yms_h5-driver-checkin"
    | "yms_h5-task-execute"
    | "yms_h5-trailer-checkin"
    | "yms_internal-task"
    | "yms_loading"
    | "yms_overview"
    | "yms_task"
    | "yms_trailer"
    | "yms_yard-inventory"
    | "yms_yard-position"
    | "yms_zone"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
