/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "base": "/base";
    "base_business-type": "/base/business-type";
    "base_channel": "/base/channel";
    "base_city": "/base/city";
    "base_company": "/base/company";
    "base_country": "/base/country";
    "base_currency": "/base/currency";
    "base_exchange-rate": "/base/exchange-rate";
    "base_fee-item": "/base/fee-item";
    "base_platform": "/base/platform";
    "base_platform-address": "/base/platform-address";
    "base_port": "/base/port";
    "base_shipping-line": "/base/shipping-line";
    "base_shipping-route": "/base/shipping-route";
    "base_sku": "/base/sku";
    "base_state-province": "/base/state-province";
    "base_terminal": "/base/terminal";
    "base_timezone": "/base/timezone";
    "base_value-added-service": "/base/value-added-service";
    "base_vessel": "/base/vessel";
    "base_warehouse": "/base/warehouse";
    "base_zip-code": "/base/zip-code";
    "comm": "/comm";
    "comm_ai": "/comm/ai";
    "comm_archive": "/comm/archive";
    "comm_business-session": "/comm/business-session";
    "comm_contacts": "/comm/contacts";
    "comm_file": "/comm/file";
    "comm_group": "/comm/group";
    "comm_meeting": "/comm/meeting";
    "comm_message": "/comm/message";
    "comm_settings": "/comm/settings";
    "comm_todo": "/comm/todo";
    "demo": "/demo";
    "demo_demo": "/demo/demo";
    "demo_tree": "/demo/tree";
    "home": "/home";
    "iec": "/iec";
    "iec_auto-flow": "/iec/auto-flow";
    "iec_credential": "/iec/credential";
    "iec_dashboard": "/iec/dashboard";
    "iec_execution-log": "/iec/execution-log";
    "iec_performance": "/iec/performance";
    "iec_role-config": "/iec/role-config";
    "iec_rpa": "/iec/rpa";
    "iec_takeover": "/iec/takeover";
    "iec_task-queue": "/iec/task-queue";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "monitor": "/monitor";
    "monitor_cache": "/monitor/cache";
    "monitor_logininfor": "/monitor/logininfor";
    "monitor_online": "/monitor/online";
    "monitor_operlog": "/monitor/operlog";
    "oms": "/oms";
    "oms_approval-flow": "/oms/approval-flow";
    "oms_business-rule": "/oms/business-rule";
    "oms_cargo-grouping-rule": "/oms/cargo-grouping-rule";
    "oms_cargo-order": "/oms/cargo-order";
    "oms_container-order": "/oms/container-order";
    "oms_inbound-plan": "/oms/inbound-plan";
    "oms_local-order": "/oms/local-order";
    "oms_local-order-detail": "/oms/local-order-detail";
    "oms_ltl-order": "/oms/ltl-order";
    "oms_ltl-order-detail": "/oms/ltl-order-detail";
    "oms_order-workbench": "/oms/order-workbench";
    "oms_outbound-order": "/oms/outbound-order";
    "oms_outbound-pool": "/oms/outbound-pool";
    "oms_platform-appointment": "/oms/platform-appointment";
    "oms_platform-order": "/oms/platform-order";
    "oms_platform-warehouse": "/oms/platform-warehouse";
    "oms_pre-outbound": "/oms/pre-outbound";
    "oms_trip-order-detail": "/oms/trip-order-detail";
    "oms_trip-recommend": "/oms/trip-recommend";
    "oms_zone-rule": "/oms/zone-rule";
    "pda": "/pda";
    "pda_business": "/pda/business";
    "pda_devanning": "/pda/devanning";
    "pda_home": "/pda/home";
    "pda_inbound": "/pda/inbound";
    "pda_outbound": "/pda/outbound";
    "pda_task": "/pda/task";
    "portal": "/portal";
    "portal_bill": "/portal/bill";
    "portal_comm": "/portal/comm";
    "portal_containers": "/portal/containers";
    "portal_exception": "/portal/exception";
    "portal_fee-confirm": "/portal/fee-confirm";
    "portal_files": "/portal/files";
    "portal_home": "/portal/home";
    "portal_in-transit": "/portal/in-transit";
    "portal_inventory": "/portal/inventory";
    "portal_order-create": "/portal/order-create";
    "portal_orders": "/portal/orders";
    "portal_settings": "/portal/settings";
    "portal_transfer-ops": "/portal/transfer-ops";
    "print": "/print";
    "print_batch": "/print/batch";
    "print_designer": "/print/designer";
    "print_permission": "/print/permission";
    "print_printer": "/print/printer";
    "print_record": "/print/record";
    "print_rule": "/print/rule";
    "print_task": "/print/task";
    "print_template-bol": "/print/template-bol";
    "print_template-carton": "/print/template-carton";
    "print_template-custom": "/print/template-custom";
    "print_template-devanning": "/print/template-devanning";
    "print_template-invoice": "/print/template-invoice";
    "print_template-location": "/print/template-location";
    "print_template-pallet-label": "/print/template-pallet-label";
    "print_template-report": "/print/template-report";
    "print_template-version": "/print/template-version";
    "print_workbench": "/print/workbench";
    "social-callback": "/social-callback";
    "system": "/system";
    "system_client": "/system/client";
    "system_config": "/system/config";
    "system_dept": "/system/dept";
    "system_dict": "/system/dict";
    "system_menu": "/system/menu";
    "system_notice": "/system/notice";
    "system_oss": "/system/oss";
    "system_oss-config": "/system/oss-config";
    "system_post": "/system/post";
    "system_role": "/system/role";
    "system_tenant": "/system/tenant";
    "system_tenant-package": "/system/tenant-package";
    "system_theme-config": "/system/theme-config";
    "system_user": "/system/user";
    "tms": "/tms";
    "tms_dispatch": "/tms/dispatch";
    "tms_dock-board": "/tms/dock-board";
    "tms_driver": "/tms/driver";
    "tms_exception": "/tms/exception";
    "tms_freight-settlement": "/tms/freight-settlement";
    "tms_home": "/tms/home";
    "tms_log": "/tms/log";
    "tms_pod": "/tms/pod";
    "tms_supplier": "/tms/supplier";
    "tms_supplier_account": "/tms/supplier/account";
    "tms_supplier_bill": "/tms/supplier/bill";
    "tms_supplier_devanning-loading": "/tms/supplier/devanning-loading";
    "tms_supplier_drayage": "/tms/supplier/drayage";
    "tms_supplier_fleet": "/tms/supplier/fleet";
    "tms_supplier_kpi": "/tms/supplier/kpi";
    "tms_supplier_linehaul": "/tms/supplier/linehaul";
    "tms_supplier_ltl": "/tms/supplier/ltl";
    "tms_supplier_quote": "/tms/supplier/quote";
    "tms_supplier-task": "/tms/supplier-task";
    "tms_vehicle": "/tms/vehicle";
    "tool": "/tool";
    "tool_gen": "/tool/gen";
    "user-center": "/user-center";
    "wms": "/wms";
    "wms_bol-pod": "/wms/bol-pod";
    "wms_devanning-dock-qr": "/wms/devanning-dock-qr";
    "wms_devanning-order": "/wms/devanning-order";
    "wms_devanning-order-detail": "/wms/devanning-order-detail";
    "wms_devanning-work": "/wms/devanning-work";
    "wms_devanning-work-exec": "/wms/devanning-work-exec";
    "wms_dock-auto-schedule": "/wms/dock-auto-schedule";
    "wms_driver-checkin": "/wms/driver-checkin";
    "wms_inventory": "/wms/inventory";
    "wms_inventory-lock": "/wms/inventory-lock";
    "wms_inventory-transaction": "/wms/inventory-transaction";
    "wms_inventory-visualization": "/wms/inventory-visualization";
    "wms_location": "/wms/location";
    "wms_operation-order": "/wms/operation-order";
    "wms_outbound-exec": "/wms/outbound-exec";
    "wms_outbound-loading": "/wms/outbound-loading";
    "wms_outbound-order": "/wms/outbound-order";
    "wms_pallet": "/wms/pallet";
    "wms_pallet-outbound": "/wms/pallet-outbound";
    "wms_stock-prep-exec": "/wms/stock-prep-exec";
    "wms_stock-prep-order": "/wms/stock-prep-order";
    "wms_stock-prep-task": "/wms/stock-prep-task";
    "wms_transfer-workbench": "/wms/transfer-workbench";
    "wms_trip-exception": "/wms/trip-exception";
    "wms_trip-fee": "/wms/trip-fee";
    "wms_trip-outbound-plan": "/wms/trip-outbound-plan";
    "wms_vas-task": "/wms/vas-task";
    "wms_vas-work": "/wms/vas-work";
    "wms_zone": "/wms/zone";
    "yard": "/yard";
    "yard_dock": "/yard/dock";
    "yard_zone": "/yard/zone";
    "yms": "/yms";
    "yms_container": "/yms/container";
    "yms_devanning": "/yms/devanning";
    "yms_dispatch": "/yms/dispatch";
    "yms_dispatch-create": "/yms/dispatch-create";
    "yms_dispatch-detail": "/yms/dispatch-detail";
    "yms_gate": "/yms/gate";
    "yms_gate-check-out": "/yms/gate-check-out";
    "yms_gate-checkin": "/yms/gate-checkin";
    "yms_gate-driver-qr": "/yms/gate-driver-qr";
    "yms_gate-in-yard": "/yms/gate-in-yard";
    "yms_gate-trailer-link": "/yms/gate-trailer-link";
    "yms_h5-driver-checkin": "/yms/h5-driver-checkin";
    "yms_h5-task-execute": "/yms/h5-task-execute";
    "yms_h5-trailer-checkin": "/yms/h5-trailer-checkin";
    "yms_internal-task": "/yms/internal-task";
    "yms_loading": "/yms/loading";
    "yms_overview": "/yms/overview";
    "yms_task": "/yms/task";
    "yms_trailer": "/yms/trailer";
    "yms_yard-inventory": "/yms/yard-inventory";
    "yms_yard-position": "/yms/yard-position";
    "yms_zone": "/yms/zone";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "base"
    | "comm"
    | "demo"
    | "home"
    | "iec"
    | "iframe-page"
    | "login"
    | "monitor"
    | "oms"
    | "pda"
    | "portal"
    | "print"
    | "social-callback"
    | "system"
    | "tms"
    | "tool"
    | "user-center"
    | "wms"
    | "yard"
    | "yms"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "social-callback"
    | "user-center"
    | "about"
    | "base_business-type"
    | "base_channel"
    | "base_city"
    | "base_company"
    | "base_country"
    | "base_currency"
    | "base_exchange-rate"
    | "base_fee-item"
    | "base_platform-address"
    | "base_platform"
    | "base_port"
    | "base_shipping-line"
    | "base_shipping-route"
    | "base_sku"
    | "base_state-province"
    | "base_terminal"
    | "base_timezone"
    | "base_value-added-service"
    | "base_vessel"
    | "base_warehouse"
    | "base_zip-code"
    | "comm_ai"
    | "comm_archive"
    | "comm_business-session"
    | "comm_contacts"
    | "comm_file"
    | "comm_group"
    | "comm_meeting"
    | "comm_message"
    | "comm_settings"
    | "comm_todo"
    | "demo_demo"
    | "demo_tree"
    | "home"
    | "iec_auto-flow"
    | "iec_credential"
    | "iec_dashboard"
    | "iec_execution-log"
    | "iec_performance"
    | "iec_role-config"
    | "iec_rpa"
    | "iec_takeover"
    | "iec_task-queue"
    | "monitor_cache"
    | "monitor_logininfor"
    | "monitor_online"
    | "monitor_operlog"
    | "oms_approval-flow"
    | "oms_business-rule"
    | "oms_cargo-grouping-rule"
    | "oms_cargo-order"
    | "oms_container-order"
    | "oms_inbound-plan"
    | "oms_local-order-detail"
    | "oms_local-order"
    | "oms_ltl-order-detail"
    | "oms_ltl-order"
    | "oms_order-workbench"
    | "oms_outbound-order"
    | "oms_outbound-pool"
    | "oms_platform-appointment"
    | "oms_platform-order"
    | "oms_platform-warehouse"
    | "oms_pre-outbound"
    | "oms_trip-order-detail"
    | "oms_trip-recommend"
    | "oms_zone-rule"
    | "pda_business"
    | "pda_devanning"
    | "pda_home"
    | "pda_inbound"
    | "pda_outbound"
    | "pda_task"
    | "portal_bill"
    | "portal_comm"
    | "portal_containers"
    | "portal_exception"
    | "portal_fee-confirm"
    | "portal_files"
    | "portal_home"
    | "portal_in-transit"
    | "portal_inventory"
    | "portal_order-create"
    | "portal_orders"
    | "portal_settings"
    | "portal_transfer-ops"
    | "print_batch"
    | "print_designer"
    | "print_permission"
    | "print_printer"
    | "print_record"
    | "print_rule"
    | "print_task"
    | "print_template-bol"
    | "print_template-carton"
    | "print_template-custom"
    | "print_template-devanning"
    | "print_template-invoice"
    | "print_template-location"
    | "print_template-pallet-label"
    | "print_template-report"
    | "print_template-version"
    | "print_workbench"
    | "system_client"
    | "system_config"
    | "system_dept"
    | "system_dict"
    | "system_menu"
    | "system_notice"
    | "system_oss-config"
    | "system_oss"
    | "system_post"
    | "system_role"
    | "system_tenant-package"
    | "system_tenant"
    | "system_theme-config"
    | "system_user"
    | "tms_dispatch"
    | "tms_dock-board"
    | "tms_driver"
    | "tms_exception"
    | "tms_freight-settlement"
    | "tms_home"
    | "tms_log"
    | "tms_pod"
    | "tms_supplier-task"
    | "tms_supplier_account"
    | "tms_supplier_bill"
    | "tms_supplier_devanning-loading"
    | "tms_supplier_drayage"
    | "tms_supplier_fleet"
    | "tms_supplier_kpi"
    | "tms_supplier_linehaul"
    | "tms_supplier_ltl"
    | "tms_supplier_quote"
    | "tms_vehicle"
    | "tool_gen"
    | "wms_bol-pod"
    | "wms_devanning-dock-qr"
    | "wms_devanning-order-detail"
    | "wms_devanning-order"
    | "wms_devanning-work-exec"
    | "wms_devanning-work"
    | "wms_dock-auto-schedule"
    | "wms_driver-checkin"
    | "wms_inventory-lock"
    | "wms_inventory-transaction"
    | "wms_inventory-visualization"
    | "wms_inventory"
    | "wms_location"
    | "wms_operation-order"
    | "wms_outbound-exec"
    | "wms_outbound-loading"
    | "wms_outbound-order"
    | "wms_pallet-outbound"
    | "wms_pallet"
    | "wms_stock-prep-exec"
    | "wms_stock-prep-order"
    | "wms_stock-prep-task"
    | "wms_transfer-workbench"
    | "wms_trip-exception"
    | "wms_trip-fee"
    | "wms_trip-outbound-plan"
    | "wms_vas-task"
    | "wms_vas-work"
    | "wms_zone"
    | "yard_dock"
    | "yard_zone"
    | "yms_container"
    | "yms_devanning"
    | "yms_dispatch-create"
    | "yms_dispatch-detail"
    | "yms_dispatch"
    | "yms_gate-check-out"
    | "yms_gate-checkin"
    | "yms_gate-driver-qr"
    | "yms_gate-in-yard"
    | "yms_gate-trailer-link"
    | "yms_gate"
    | "yms_h5-driver-checkin"
    | "yms_h5-task-execute"
    | "yms_h5-trailer-checkin"
    | "yms_internal-task"
    | "yms_loading"
    | "yms_overview"
    | "yms_task"
    | "yms_trailer"
    | "yms_yard-inventory"
    | "yms_yard-position"
    | "yms_zone"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
